[theme]
base = "light"
primaryColor = "#0787a6"
backgroundColor = "#dcebef"
secondaryBackgroundColor = "#edf6f8"
textColor = "#102f3b"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true

